name: release

on:
    push:
        branches: [docs]
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
              with:
                fetch-depth: 0
            - name: Install dependencies
              run: python3 -m pip install -r requirements.txt
            - name: Build docs
              run: make github_actions_docs
            - name: Commit built docs
              run: |
                  git config --global user.name "github-actions[bot]"
                  git config --global user.email "github-actions[bot]@users.noreply.github.com"
                  git add docs
                  git commit -m "new github pages"
                  git push
